CREATE TABLE IF NOT EXISTS public.solicitudes_equipos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(30) NOT NULL UNIQUE,
    estado varchar(30) NOT NULL DEFAULT 'ESPERA_APROBACION',
    ubicacion_origen_id bigint NOT NULL REFERENCES public.ubicaciones(id),
    ubicacion_destino_id bigint NOT NULL REFERENCES public.ubicaciones(id),
    fecha_envio timestamp with time zone NOT NULL,
    guia varchar(150),
    transportista varchar(150),
    solicitante_usuario_id bigint,
    solicitante_nombre varchar(150) NOT NULL,
    aprobado_por_usuario_id bigint,
    aprobado_por_nombre varchar(150),
    fecha_aprobacion timestamp with time zone,
    recibido_por_usuario_id bigint,
    recibido_por_nombre varchar(150),
    fecha_recepcion timestamp with time zone,
    observaciones_salida text,
    observaciones_recepcion text,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT solicitudes_equipos_estado_valido CHECK (
        estado IN ('ESPERA_APROBACION', 'EN_CAMINO', 'RECIBIDO')
    ),
    CONSTRAINT solicitudes_equipos_ubicaciones_distintas CHECK (
        ubicacion_origen_id <> ubicacion_destino_id
    )
);

CREATE TABLE IF NOT EXISTS public.solicitudes_equipos_detalle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL REFERENCES public.solicitudes_equipos(id) ON DELETE CASCADE,
    inventario_id bigint NOT NULL REFERENCES public.inventario(id),
    cantidad numeric(14,3) NOT NULL CHECK (cantidad > 0),
    condicion_salida_id bigint REFERENCES public.condiciones(id),
    calibracion_salida varchar(20),
    condicion_recepcion_id bigint REFERENCES public.condiciones(id),
    calibracion_recepcion varchar(20),
    observaciones text,
    CONSTRAINT solicitudes_detalle_calibracion_salida_valida CHECK (
        calibracion_salida IS NULL OR calibracion_salida IN ('NO_CUMPLE', 'SIN_CALIBRAR', 'CALIBRADO')
    ),
    CONSTRAINT solicitudes_detalle_calibracion_recepcion_valida CHECK (
        calibracion_recepcion IS NULL OR calibracion_recepcion IN ('NO_CUMPLE', 'SIN_CALIBRAR', 'CALIBRADO')
    )
);

CREATE TABLE IF NOT EXISTS public.solicitudes_equipos_historial (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL REFERENCES public.solicitudes_equipos(id) ON DELETE CASCADE,
    estado_anterior varchar(30),
    estado_nuevo varchar(30) NOT NULL,
    usuario_id bigint,
    usuario_nombre varchar(150) NOT NULL,
    comentario text,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT solicitudes_historial_estado_nuevo_valido CHECK (
        estado_nuevo IN ('ESPERA_APROBACION', 'EN_CAMINO', 'RECIBIDO')
    )
);

CREATE INDEX IF NOT EXISTS ix_solicitudes_equipos_estado
    ON public.solicitudes_equipos (estado);

CREATE INDEX IF NOT EXISTS ix_solicitudes_equipos_solicitante
    ON public.solicitudes_equipos (solicitante_nombre);

CREATE INDEX IF NOT EXISTS ix_solicitudes_equipos_fecha
    ON public.solicitudes_equipos (creado_en DESC);

CREATE INDEX IF NOT EXISTS ix_solicitudes_detalle_solicitud
    ON public.solicitudes_equipos_detalle (solicitud_id);

CREATE INDEX IF NOT EXISTS ix_solicitudes_historial_solicitud
    ON public.solicitudes_equipos_historial (solicitud_id, creado_en);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    public.solicitudes_equipos,
    public.solicitudes_equipos_detalle,
    public.solicitudes_equipos_historial
TO inventario_importador;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
TO inventario_importador;
