BEGIN;

CREATE TABLE IF NOT EXISTS public.solicitudes_equipos_archivos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL
        REFERENCES public.solicitudes_equipos(id)
        ON DELETE CASCADE,
    tipo varchar(30) NOT NULL,
    nombre_original varchar(255) NOT NULL,
    nombre_almacenado varchar(255) NOT NULL,
    ruta_remota text NOT NULL,
    mime_type varchar(100) NOT NULL,
    tamano_bytes bigint NOT NULL,
    sha256 char(64) NOT NULL,
    nextcloud_file_id varchar(255),
    nextcloud_etag varchar(255),
    subido_por_usuario_id bigint,
    subido_por_nombre varchar(150) NOT NULL,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    eliminado_en timestamp with time zone,
    eliminado_por_nombre varchar(150),
    CONSTRAINT solicitudes_archivos_tipo_valido CHECK (
        tipo IN ('DOCUMENTO', 'FIRMA_REMITENTE', 'FIRMA_RECEPTOR')
    ),
    CONSTRAINT solicitudes_archivos_tamano_valido CHECK (
        tamano_bytes > 0
    ),
    CONSTRAINT solicitudes_archivos_sha256_valido CHECK (
        sha256 ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT solicitudes_archivos_mime_valido CHECK (
        (tipo = 'DOCUMENTO' AND mime_type = 'application/pdf')
        OR
        (
            tipo IN ('FIRMA_REMITENTE', 'FIRMA_RECEPTOR')
            AND mime_type = 'image/png'
        )
    ),
    CONSTRAINT solicitudes_archivos_eliminacion_valida CHECK (
        eliminado_en IS NOT NULL OR eliminado_por_nombre IS NULL
    ),
    CONSTRAINT solicitudes_archivos_ruta_unica UNIQUE (ruta_remota)
);

CREATE INDEX IF NOT EXISTS ix_solicitudes_archivos_solicitud
    ON public.solicitudes_equipos_archivos
    (solicitud_id, creado_en DESC)
    WHERE eliminado_en IS NULL;

CREATE INDEX IF NOT EXISTS ix_solicitudes_archivos_sha256
    ON public.solicitudes_equipos_archivos (sha256);

CREATE UNIQUE INDEX IF NOT EXISTS ux_solicitudes_archivos_firma_activa
    ON public.solicitudes_equipos_archivos (solicitud_id, tipo)
    WHERE tipo IN ('FIRMA_REMITENTE', 'FIRMA_RECEPTOR')
      AND eliminado_en IS NULL;

COMMENT ON TABLE public.solicitudes_equipos_archivos IS
    'Metadatos de documentos y firmas de solicitudes. El contenido se almacena en Nextcloud.';

COMMENT ON COLUMN public.solicitudes_equipos_archivos.ruta_remota IS
    'Ruta relativa privada dentro de TI/STP-INVENTORY en Nextcloud.';

COMMENT ON COLUMN public.solicitudes_equipos_archivos.sha256 IS
    'Hash SHA-256 del contenido para comprobar su integridad.';

COMMENT ON COLUMN public.solicitudes_equipos_archivos.eliminado_en IS
    'Eliminacion logica del metadato; el backend elimina también el archivo remoto.';

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.solicitudes_equipos_archivos
TO inventario_importador;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
TO inventario_importador;

COMMIT;
