BEGIN;

CREATE TABLE IF NOT EXISTS public.inventario_archivos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventario_id bigint NOT NULL
        REFERENCES public.inventario(id)
        ON DELETE CASCADE,
    descripcion varchar(500) NOT NULL,
    nombre_original varchar(255) NOT NULL,
    nombre_almacenado varchar(255) NOT NULL,
    ruta_remota text NOT NULL,
    mime_type varchar(100) NOT NULL DEFAULT 'application/pdf',
    tamano_bytes bigint NOT NULL,
    sha256 char(64) NOT NULL,
    nextcloud_file_id varchar(255),
    nextcloud_etag varchar(255),
    subido_por_nombre varchar(150) NOT NULL,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    eliminado_en timestamp with time zone,
    eliminado_por_nombre varchar(150),
    CONSTRAINT inventario_archivos_descripcion_valida CHECK (
        length(btrim(descripcion)) >= 2
    ),
    CONSTRAINT inventario_archivos_mime_valido CHECK (
        mime_type = 'application/pdf'
    ),
    CONSTRAINT inventario_archivos_tamano_valido CHECK (
        tamano_bytes > 0 AND tamano_bytes <= 20971520
    ),
    CONSTRAINT inventario_archivos_sha256_valido CHECK (
        sha256 ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT inventario_archivos_eliminacion_valida CHECK (
        eliminado_en IS NOT NULL OR eliminado_por_nombre IS NULL
    ),
    CONSTRAINT inventario_archivos_ruta_unica UNIQUE (ruta_remota)
);

CREATE INDEX IF NOT EXISTS ix_inventario_archivos_inventario
    ON public.inventario_archivos (inventario_id, creado_en DESC)
    WHERE eliminado_en IS NULL;

CREATE INDEX IF NOT EXISTS ix_inventario_archivos_sha256
    ON public.inventario_archivos (sha256);

COMMENT ON TABLE public.inventario_archivos IS
    'Metadatos de documentos PDF vinculados a articulos. El contenido se almacena en Nextcloud.';

COMMENT ON COLUMN public.inventario_archivos.descripcion IS
    'Descripcion administrativa obligatoria del documento.';

COMMENT ON COLUMN public.inventario_archivos.ruta_remota IS
    'Ruta relativa privada dentro de TI/STP-INVENTORY en Nextcloud.';

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.inventario_archivos
TO inventario_importador;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
TO inventario_importador;

COMMIT;
