BEGIN;

CREATE TABLE IF NOT EXISTS public.modalidades_almacenamiento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL UNIQUE,
    descripcion text,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now()
);

INSERT INTO public.modalidades_almacenamiento (nombre, descripcion)
VALUES
    ('CAJA', 'Articulo almacenado dentro de una caja identificada.'),
    ('ESTANTE', 'Articulo asignado a un estante identificado.'),
    ('RACK', 'Articulo asignado a un rack identificado.'),
    ('GABINETE', 'Articulo almacenado dentro de un gabinete identificado.'),
    ('PALLET', 'Articulo agrupado sobre un pallet identificado.'),
    ('OTRO', 'Otra modalidad de almacenamiento especifico.')
ON CONFLICT (nombre) DO NOTHING;

ALTER TABLE public.inventario
    ADD COLUMN IF NOT EXISTS modalidad_almacenamiento_id bigint,
    ADD COLUMN IF NOT EXISTS referencia_almacenamiento varchar(100),
    ADD COLUMN IF NOT EXISTS detalle_almacenamiento text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'inventario_modalidad_almacenamiento_fk'
          AND conrelid = 'public.inventario'::regclass
    ) THEN
        ALTER TABLE public.inventario
            ADD CONSTRAINT inventario_modalidad_almacenamiento_fk
            FOREIGN KEY (modalidad_almacenamiento_id)
            REFERENCES public.modalidades_almacenamiento(id);
    END IF;
END
$$;

ALTER TABLE public.inventario
    DROP CONSTRAINT IF EXISTS inventario_almacenamiento_especifico_valido;

ALTER TABLE public.inventario
    ADD CONSTRAINT inventario_almacenamiento_especifico_valido CHECK (
        (
            modalidad_almacenamiento_id IS NULL
            AND referencia_almacenamiento IS NULL
            AND detalle_almacenamiento IS NULL
        )
        OR
        (
            modalidad_almacenamiento_id IS NOT NULL
            AND referencia_almacenamiento IS NOT NULL
            AND length(btrim(referencia_almacenamiento)) >= 1
        )
    );

CREATE INDEX IF NOT EXISTS ix_inventario_modalidad_almacenamiento
    ON public.inventario (modalidad_almacenamiento_id)
    WHERE modalidad_almacenamiento_id IS NOT NULL;

COMMENT ON TABLE public.modalidades_almacenamiento IS
    'Catalogo editable de formas opcionales de almacenamiento especifico.';

COMMENT ON COLUMN public.inventario.referencia_almacenamiento IS
    'Identificador fisico opcional, por ejemplo CAJA-015, RACK-02 o ESTANTE-B.';

COMMENT ON COLUMN public.inventario.detalle_almacenamiento IS
    'Indicaciones adicionales para localizar el articulo dentro de su ubicacion.';

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.modalidades_almacenamiento
TO inventario_importador;

GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.inventario
TO inventario_importador;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
TO inventario_importador;

COMMIT;
